config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # get "/teste", to: "static#index"
  root "static#index"

  resources :users
  resources :avaliable_lots, only: [ :index ]
  resources :tables

  resources :products do
    resources :lots
  end

  resources :orders do
    resources :orders_lots, only: [ :new, :create, :destroy ] do
      member do
        post :order_lot_delivered
      end
    end

    member do
      post :close_order
    end
  end

  get "dashboard", to: "dashboard#show"
  get "delivery", to: "delivery#index"

  get "forbidden", to: "errors#forbidden"
  get "not_found", to: "errors#not_found"

  match "/404", to: "errors#not_found", via: :all
  match "/403", to: "errors#forbidden", via: :all
  match "/500", to: "errors#internal_server_error", via: :all


  get "/login", to: "sessions#index"
  post "/login", to: "sessions#login"
  get "/logout", to: "sessions#logout"

  patch "users/:id/update_password", to: "users#update_password", as: :password_update
end

app/views/shared/_alert.html.erb
<% if notice.present? || alert.present? %>
  <div id="flash-message" class="max-w-4xl mx-auto mt-6">
    <div class="<%= notice.present? ? 'bg-green-100 border border-green-400 text-green-700' : 'bg-red-100 border border-red-400 text-red-700' %> px-6 py-4 rounded-md shadow">
      <p class="text-sm font-medium"><%= notice.presence || alert.presence %></p>
    </div>
  </div>
<% end %>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    const flashMessage = document.getElementById("flash-message");
    if (flashMessage) {
      setTimeout(() => {
        flashMessage.classList.add('opacity-0', 'transition', 'duration-500');
        setTimeout(() => flashMessage.remove(), 500);
      }, 4000);
    }
  });
</script>

app/views/shared/_footer.html.erb
  <footer class="text-center text-sm text-[#6b4226] py-6 border-t border-[#f5cfc3]">
    &copy; 2025 Sistema Confeitaria. Todos os direitos reservados.
  </footer>

app/views/shared/_navbar.html.erb
<% if @current_user %>
  <nav class="bg-white shadow-md">
    <div class="max-w-7xl mx-auto px-6 py-4 flex justify-between items-center">

      <div class="text-3xl font-bold text-[#c2410c] tracking-wide hover:text-[#9a3412] transition">
        <%= link_to "Candy Shop", root_path %>
      </div>

      <div class="flex items-center space-x-6">
      
      <div class="hidden md:flex space-x-8 text-sm font-medium items-center">
        <%= link_to 'Mesas', tables_path, class: 'text-base text-[#9a3412] hover:text-[#c2410c] hover:scale-105 transition' %>  
        <%= link_to 'Balcão', delivery_path, class: 'text-base text-[#9a3412] hover:text-[#c2410c] hover:scale-105 transition' %>  
        <%= link_to 'Produtos', products_path, class: 'text-base text-[#9a3412] hover:text-[#c2410c] hover:scale-105 transition' %>
        <% if @current_user.is_admin %>
            <%= link_to 'Pedidos', orders_path, class: 'text-base text-[#9a3412] hover:text-[#c2410c] hover:scale-105 transition' %>
            <%= link_to 'Membros', users_path, class: 'text-base text-[#9a3412] hover:text-[#c2410c] hover:scale-105 transition' %>
            <%= link_to 'Dashboard', dashboard_path, class: 'text-base text-[#9a3412] hover:text-[#c2410c] hover:scale-105 transition' %>
          <% end %>
        </div>

        <div class="flex items-center space-x-4">

          <div data-controller="dropdown" class="relative">
            <button data-action="click->dropdown#toggle" class="flex items-center space-x-2 focus:outline-none">
              <img src="https://ui-avatars.com/api/?background=c2410c&color=fff&name=<%= @current_user.name %>" alt="Avatar" class="w-10 h-10 rounded-full border-2 border-gray-700">
            </button>
            <div data-dropdown-target="menu" class="hidden absolute right-0 mt-2 w-72 bg-white rounded-md shadow-xl z-50">
              <div class="flex items-center space-x-4 px-4 py-4 border-b border-gray-200">
                <img src="https://ui-avatars.com/api/?background=c2410c&color=fff&name=<%= @current_user.name %>" alt="Avatar" class="w-14 h-14 rounded-full border">
                <div>
                  <p class="text-base font-semibold text-gray-800"><%= @current_user.name %></p>
                  <p class="text-sm text-gray-500">  <%= @current_user.cpf.gsub(/(\d{3})(\d{3})(\d{3})(\d{2})/, '\1.\2.\3-\4') %></p>
                </div>
              </div>
              <div class="py-2">
                <%= link_to 'Minha Conta', @current_user, class: 'block px-4 py-2 text-base text-[#9a3412] hover:text-[#c2410c] transition hover:bg-gray-100' %>
                <%= link_to 'Sair', logout_path, method: :get, class: 'block px-4 py-2 text-base text-[#9a3412] hover:text-[#c2410c] transition hover:bg-gray-100' %>
              </div>
            </div>
          </div>
      </div>


        <div data-controller="dropdown" class="md:hidden">
          <button data-action="click->dropdown#toggle" class="text-[#c2410c] hover:text-[#9a3412]">
            <svg class="w-7 h-7" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
            </svg>
          </button>
          <div data-dropdown-target="menu" class="hidden absolute right-4 top-14 bg-white rounded-md shadow-lg py-2 w-56 z-50">
            <%= link_to 'Mesas', tables_path, class: 'block px-4 py-2 text-base text-[#9a3412] hover:text-[#c2410c] transition hover:bg-gray-100' %>  
            <%= link_to 'Balcão', delivery_path, class: 'block px-4 py-2 text-base text-[#9a3412] hover:text-[#c2410c] transition hover:bg-gray-100' %>  
            <%= link_to 'Produtos', products_path, class: 'block px-4 py-2 text-base text-[#9a3412] hover:text-[#c2410c] transition hover:bg-gray-100' %>
            <% if @current_user.is_admin %>
              <%= link_to 'Pedidos', orders_path, class: 'block px-4 py-2 text-base text-[#9a3412] hover:text-[#c2410c] transition hover:bg-gray-100' %>
              <%= link_to 'Membros', users_path, class: 'block px-4 py-2 text-base text-[#9a3412] hover:text-[#c2410c] transition hover:bg-gray-100' %>
              <%= link_to 'Dashboard', dashboard_path, class: 'block px-4 py-2 text-base text-[#9a3412] hover:text-[#c2410c] transition hover:bg-gray-100' %>
            <% end %>
          </div>
        </div>

      </div>
    </div>
  </nav>
<% end %>