config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # get "/teste", to: "static#index"
  root "static#index"

  resources :users
  resources :avaliable_lots, only: [ :index ]
  resources :tables

  resources :products do
    resources :lots
  end

  resources :orders do
    resources :orders_lots, only: [ :new, :create, :destroy ] do
      member do
        post :order_lot_delivered
      end
    end

    member do
      post :close_order
    end
  end

  get "dashboard", to: "dashboard#show"
  get "delivery", to: "delivery#index"

  get "forbidden", to: "errors#forbidden"
  get "not_found", to: "errors#not_found"

  match "/404", to: "errors#not_found", via: :all
  match "/403", to: "errors#forbidden", via: :all
  match "/500", to: "errors#internal_server_error", via: :all


  get "/login", to: "sessions#index"
  post "/login", to: "sessions#login"
  get "/logout", to: "sessions#logout"

  patch "users/:id/update_password", to: "users#update_password", as: :password_update
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :lots, dependent: :destroy

    validates :name, uniqueness: { case_sensitive: false, message: "do produto ja esta em uso" }, presence: true
    validates :name, presence: true
    validates :description, presence: true
    validates :category, presence: true
    validates :price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [ :show, :edit, :update, :destroy ]
  before_action :is_admin?, only: %i[create new edit update destroy]

  def index
    @products = Product.all
    respond_to do |format|
      format.html
      format.json do
        if @products.any?
          render json: @products
        else
          head :no_content
        end
      end
    end
  end

  def show
    respond_to do |format|
      format.html
      format.json do
        if @product
          render json: @product
        else
          head :not_found
        end
      end
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)

    if @product.save
      respond_to do |format|
        format.json { render json: @product, status: :created }
        format.html { redirect_to @product, notice: "Produto criado com sucesso." }
      end
    else
      respond_to do |format|
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end


  def edit
  end

  def update
    if @product.update(product_params)
      respond_to do |format|
        format.json { render json: @product, status: :ok }
        format.html { redirect_to @product, notice: "Produto atualizado com sucesso." }
      end
    else
      respond_to do |format|
        format.json { render json: @product.errors, status: :unprocessable_entity }
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    if @current_user&.is_admin
      @product.destroy
      respond_to do |format|
        format.json { render json: { message: "#{@product.name} deleted" }, status: :ok }
        format.html { redirect_to products_url, notice: "Produto removido com sucesso." }
      end
    else
      redirect_to products_url, notice: "Apenas administradores podem remover produtos."
    end
  end

  def inventory
    @product = Product.find(params[:id])
    @lots = @product.lots.order(created_at: :desc)
  end

  private

  def is_admin?
    unless @current_user&.is_admin
      respond_to do |format|
        format.html { redirect_to products_url, notice: "Apenas administradores podem fazer isso" }
        format.json { render json: { error: "Apenas administradores podem fazer isso" }, status: :forbidden }
      end
    end
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, :category, :price)
  end
end

app/views/products/edit.html.erb
<%= render 'shared/alert' %>

<div class="max-w-2xl mx-auto py-10 px-4">
  <div class="bg-white shadow-xl rounded-2xl overflow-hidden">
    <div class="px-6 py-5 border-b border-gray-200 flex justify-between items-center">
      <h1 class="text-2xl font-semibold text-gray-700 flex items-center">Editar Produto</h1>
      <%= link_to "Voltar", products_path, 
        class: 'text-sm px-4 py-2 border border-gray-400 text-gray-700 rounded hover:bg-gray-700 hover:border-gray-700 hover:text-white transition', 
        title: 'Voltar para a lista de produtos'%>
    </div>
    <div class="px-6 py-8">
      <%= form_with(model: @product, local: true) do |form| %>
        <% if @product.errors.any? %>
          <div class="bg-red-100 text-red-800 px-4 py-3 rounded mb-6">
            <h2 class="font-semibold mb-2">Foram encontrados erros:</h2>
            <ul class="list-disc pl-5">
              <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-6">
          <%= form.label :name, 'Nome', class: 'block text-gray-700 font-medium mb-1' %>
          <%= form.text_field :name, 
              class: "block w-full px-4 py-3 rounded-xl border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none text-base transition",
              autofocus: true,
              required: true,
              placeholder: "Digite o nome do produto"
          %>
        </div>

        <div class="mb-6">
          <%= form.label :category, 'Categoria', class: 'block text-gray-700 font-medium mb-1' %>
          <%= form.text_field :category, 
              class: "block w-full px-4 py-3 rounded-xl border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none text-base transition",
              autofocus: true,
              required: true,
              placeholder: "Digite a categoria do produto"
          %>
        </div>
        

        <div class="mb-6">
          <%= form.label :description, 'Descrição', class: 'block text-gray-700 font-medium mb-1' %>
          <%= form.text_area :description, rows: 4, 
              class: "block w-full px-4 py-3 rounded-xl border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none text-base transition",
              autofocus: true,
              required: true,
              placeholder: "Digite a descrição do produto"
          %>
        </div>

        <div class="mb-8">
          <%= form.label :price, 'Preço', class: 'block text-gray-700 font-medium mb-1' %>
          <div class="flex items-center">        
            <span class="inline-block px-4 py-3 border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none text-base transition border-r-0 rounded-l-xl">R$</span>
            <%= form.number_field :price, step: 0.01, min: 0, 
              class: "w-full px-4 py-3 rounded-r-xl border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none text-base transition ",
              autofocus: true,
              required: true,
              placeholder: "Digite o preço do produto"
            %>  
          </div>
        </div>

        <div class="flex justify-end space-x-2">
          <%= link_to 'Cancelar', products_path, class: 'px-4 py-2 border border-gray-300 rounded text-gray-600 hover:bg-gray-100 transition' %>
          <%= form.submit 'Salvar', class: 'px-6 py-2 bg-indigo-600 text-white rounded hover:bg-indigo-700 transition font-semibold flex items-center' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="max-w-5xl mx-auto px-4 py-8">
  <div class="flex justify-between items-center mb-6">
    <h1 class="text-4xl font-bold text-gray-900">Lista de Produtos</h1>
    <% if @current_user.is_admin? %>  
      <%= link_to  "Novo Produto", new_product_path, class: "inline-flex items-center px-5 py-2.5 rounded-xl text-sm font-semibold text-white bg-[#c2410c] text-white text-sm font-medium rounded-md hover:bg-[#9a3412] transition"%> 
    <% end %>
  </div>

  <% if @products.any? %>
    <ul class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      <% @products.each do |product| %>
        <li>
          <%= link_to product_path(product), class: "bg-white rounded-xl shadow hover:shadow-lg transition duration-200 p-5 flex flex-col justify-between h-full block hover:scale-105 transition" do %>
          <div class="mb-3">
            <h2 class="text-lg font-semibold text-gray-700 mb-1 hover:text-[#c2410c] transition">
              <%= product.name %>
            </h2>
            <% if product.category.present? %>
              <span class="inline-block bg-red-100 text-red-800 text-xs px-2 py-1 rounded">
                <%= product.category %>
              </span>
            <% end %>
          </div>

          <div class="mt-auto flex justify-between items-center text-sm text-gray-500">
            <span><i class="fas fa-boxes mr-1"></i> <%= product.lots.sum(:quantity) %> unidades</span>
            <span class="font-medium text-red-600"><%= number_to_currency(product.price, unit: "R$", separator: ",", delimiter: ".", format: "%u %n") %></span>
          </div>
        <% end %>
      </li>
      <% end %>
    </ul>
  <% else %>
    <div class="bg-white shadow overflow-hidden border-l-4 border-gray-500 sm:rounded-md mb-8 mt-6">
      <p class="px-4 py-6 text-gray-600">Nenhum produto cadastrado.</p>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<%= render 'shared/alert' %>

<div class="max-w-2xl mx-auto py-10 px-4">
  <div class="bg-white shadow-xl rounded-2xl overflow-hidden">
    <div class="px-6 py-5 border-b border-gray-200 flex justify-between items-center">
      <h1 class="text-2xl font-semibold text-gray-800 flex items-center">Novo Produto</h1>
      <%= link_to "Voltar", products_path, 
        class: 'text-sm px-4 py-2 border border-gray-400 text-gray-700 rounded hover:bg-gray-700 hover:border-gray-700 hover:text-white transition', 
        title: 'Voltar para a lista de produtos'
      %>
    </div>
    <div class="px-6 py-8">
      <%= form_with(model: @product, local: true) do |form| %>
        <% if @product.errors.any? %>
          <div class="bg-red-100 text-red-800 px-4 py-3 rounded mb-6">
            <h2 class="font-semibold mb-2">Foram encontrados erros:</h2>
            <ul class="list-disc pl-5">
              <% @product.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="mb-6">
          <%= form.label :name, 'Nome', class: 'block text-gray-700 font-medium mb-1' %>
          <%= form.text_field :name, 
              class: "block w-full px-4 py-3 rounded-xl border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none text-base transition",
              autofocus: true,
              required: true,
              placeholder: "Digite o nome do produto"
          %>
        </div>

        <div class="mb-6">
          <%= form.label :category, 'Categoria', class: 'block text-gray-700 font-medium mb-1' %>
          <%= form.text_field :category, 
              class: "block w-full px-4 py-3 rounded-xl border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none text-base transition",
              autofocus: true,
              required: true,
              placeholder: "Digite a categoria do produto"
          %>
        </div>
        

        <div class="mb-6">
          <%= form.label :description, 'Descrição', class: 'block text-gray-700 font-medium mb-1' %>
          <%= form.text_area :description, rows: 4, 
              class: "block w-full px-4 py-3 rounded-xl border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none text-base transition",
              autofocus: true,
              required: true,
              placeholder: "Digite a descrição do produto"
          %>
        </div>

        <div class="mb-8">
          <%= form.label :price, 'Preço', class: 'block text-gray-700 font-medium mb-1' %>
          <div class="flex items-center">        
            <span class="inline-block px-4 py-3 border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none text-base transition border-r-0 rounded-l-xl">R$</span>
            <%= form.number_field :price, step: 0.01, min: 0, 
              class: "w-full px-4 py-3 rounded-r-xl border border-gray-300 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-500 focus:outline-none text-base transition ",
              autofocus: true,
              required: true,
              placeholder: "Digite o preço do produto"
            %>  
          </div>
        </div>


        <div class="flex justify-end space-x-2">
          <%= link_to 'Cancelar', products_path, class: 'px-4 py-2 border border-gray-300 rounded text-gray-600 hover:bg-gray-100 transition' %>
          <%= form.submit 'Salvar', class: 'px-6 py-2 bg-indigo-600 text-white rounded hover:bg-indigo-700 transition font-semibold flex items-center' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<%= render 'shared/alert' %>

<div class="max-w-7xl mx-auto py-10 px-4">
  <div class="bg-white shadow-xl rounded-2xl overflow-hidden">
    <div class="px-6 py-5 border-b border-gray-200 flex justify-between items-center">
      <h1 class="text-2xl font-semibold text-gray-800 flex items-center"> <%= @product.name %> </h1>
      <div class="flex space-x-2">
        <% if @current_user.is_admin? %>  

          <%= link_to "Editar", edit_product_path(@product), 
              class: 'text-sm px-4 py-2 border border-indigo-500 text-indigo-600 rounded hover:bg-indigo-600 hover:text-white transition', 
              title: 'Editar produto'
            %>
        <% end %>
          <%= link_to "Voltar", products_path, 
          class: 'text-sm px-4 py-2 border border-gray-400 text-gray-700 rounded hover:bg-gray-700 hover:border-gray-700 hover:text-white transition', 
          title: 'Voltar para a lista de produtos'
        %>
      </div>
    </div>

    <div class="px-6 py-8 grid grid-cols-1 md:grid-cols-2 gap-8">

      <div>
        <h2 class="text-gray-600 text-lg mb-3">📋 Informações do Produto</h2>
        <span class="inline-block bg-red-100 text-red-800 text-sm px-3 py-1 rounded-full mb-4"><%= @product.category %></span>
        <p class="text-gray-800 text-base mb-6"><%= @product.description %></p>

        <div class="mb-6">
          <h3 class="text-gray-500 text-sm">💰 Preço</h3>
          <div class="text-2xl font-bold text-gray-800 mt-1"><%= number_to_currency(@product.price, unit: "R$", separator: ",", delimiter: ".", format: "%u %n") %></div>
        </div>

        <hr class="border-t border-gray-200 my-6">

        <!-- Estoque -->
        <h2 class="text-gray-600 text-lg mb-3">📦 Detalhes do Estoque</h2>
        <div class="bg-gray-50 p-4 rounded-lg shadow">
          <div class="flex justify-between items-center mb-4">
            <div>
              <p class="text-sm text-gray-500 mb-1">Estoque Total</p>
              <div class="text-xl font-semibold text-gray-800"><%= @product.lots.sum(:quantity) %> unidades</div>
            </div>
              <% if @current_user.is_admin? %>  
                <%= link_to "Gerenciar", product_lots_path(@product), class: 'bg-indigo-600 text-white text-sm px-4 py-2 rounded hover:bg-indigo-700 transition' %>
              <% end %>
            </div>

          <% if @product.lots.any? %>
            <p class="text-xs uppercase text-gray-400 mb-2">Lotes disponíveis</p>
            <ul class="space-y-4">
             
            </ul>
          <% else %>
            <div class="bg-yellow-100 text-yellow-800 text-sm p-4 rounded flex items-center mt-4">Nenhum lote cadastrado para este produto.</div>
          <% end %>
        </div>
      </div>

      <div class="flex items-center justify-center">
        <div class="border border-gray-200 bg-white rounded-lg shadow w-full flex flex-col items-center justify-center py-20">
          <p class="text-sm text-gray-500">Imagem do produto</p>
          <span class="text-xs text-gray-400">Funcionalidade futura de upload</span>
        </div>
      </div>
    </div>

    <!-- Rodapé -->
    <div class="bg-gray-50 border-t border-gray-200 px-6 py-4 text-sm text-gray-500 flex justify-between">
      <div>Criado em: <%= l(@product.created_at, format: :long) %></div>
      <div>Atualizado em: <%= l(@product.updated_at, format: :long) %></div>
    </div>
  </div>
</div>